In [ ]:
100 e kadar rastgele tamsayılardan oluşan 3,3 bir matris oluşturun
30 dan büyük olanları boolean yöntemi ile filtreleyin.

In [3]:
import numpy as np

# 3x3 matrisi rastgele tamsayılarla oluştur
random_matrix = np.random.randint(0, 100, size=(3, 3))

print("Oluşturulan Rastgele Matris:")
print(random_matrix)

# Matristeki 30'dan büyük olanları boolean filtreleme ile seç
filtered_matrix = random_matrix > 30

print("\n30'dan Büyük Olanlar:")
print(filtered_matrix)

ModuleNotFoundError: No module named 'numpy'

In [ ]:
import numpy as np

populasyon = np.random.randint(0, 100, size=100)

ortalama = np.mean(populasyon)
standart_sapma = np.std(populasyon)

condition = (populasyon > ortalama) | (standart_sapma/2 + ortalama > populasyon)

print("Ortalamadan büyük olanlar veya std/2 ile ortalamasının toplamı popülasyondan az olanlar:")
print(populasyon[condition])

In [ ]:
result = populasyon[(populasyon > np.mean(populasyon)) | (populasyon < np.std(populasyon)/2 + np.mean(populasyon))]

In [3]:
number = 15

In [4]:
type(number)

int

In [5]:
dir(number)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 '

In [6]:
my_list = [1, 2, 3]

In [7]:
dir(my_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

## NUMPY

In [8]:
import numpy as np

In [9]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [10]:
array_a = np.array([1, 2, 3, 4])

In [11]:
array_b = np.array([0, .5, 1, 1.5, 2])

In [12]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [13]:
array_a[0]

1

In [14]:
array_b[-1]

2.0

In [15]:
array_a[:2]

array([1, 2])

In [16]:
array_a.dtype

dtype('int32')

In [17]:
array_b.dtype

dtype('float64')

In [18]:
empty_array = np.array([])

In [19]:
empty_array.dtype

dtype('float64')

In [20]:
np.array([1, 2, 3, 4], dtype=np.float_)

array([1., 2., 3., 4.])

In [21]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [22]:
array_c = np.array(["ada", "lovelace"])

In [23]:
array_c.dtype

dtype('<U8')

## Dimemsion and shapes

In [24]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [25]:
array_a.shape

(4,)

In [26]:
my_array.shape

(2, 3)

In [27]:
array_a.ndim

1

In [28]:
my_array.ndim

2

In [29]:
my_array.size

6

In [30]:
my_array = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 6],
        [3, 2, 1]
    ]
])

In [31]:
my_array.ndim

3

In [32]:
my_array.shape

(2, 2, 3)

In [33]:
my_array.size

12

#indexing and slicing

In [34]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]    
])

In [35]:
my_array[1]

array([4, 5, 6])

In [36]:
my_array[1][0]

4

In [37]:
my_array[1, 0]

4

In [38]:
my_array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
my_array[:2, :2]

array([[1, 2],
       [4, 5]])

In [40]:
my_array[1] = np.array([10, 10, 10])

In [41]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [42]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [43]:
my_array = np.arange(0,10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
my_array.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [45]:
np.arange(1, 10.1, 4)

array([1., 5., 9.])

In [46]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [47]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [48]:
np.ones((2, 5, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [49]:
my_array = np.random.random((5,2))

In [50]:
my_array

array([[0.43135092, 0.68758403],
       [0.17935327, 0.01763784],
       [0.64683877, 0.4434165 ],
       [0.58404207, 0.77719778],
       [0.90492342, 0.00144458]])

In [51]:
np.random.randint(100, size=(5, 5))

array([[ 8, 50, 12,  1, 61],
       [88, 42, 54, 39, 73],
       [18, 54, 75, 84, 89],
       [22, 81,  0, 79, 69],
       [98, 16, 33, 79, 92]])

In [52]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

# any(), all(), full(), concatenate()

In [53]:
array1 = np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
array1 = array1.reshape(2, 5)

In [55]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
np.concatenate([array1, array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
np.concatenate([array1, array1], axis=1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

# statistic

In [61]:
array1 = np.arange(0, 10)
array1 = array1.reshape(2, 5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
array1.sum()


45

In [63]:
array1.mean()

4.5

In [64]:
array1.std()

2.8722813232690143

In [65]:
array1.var()

8.25

In [66]:
array1.sum(axis=1)

array([10, 35])

In [67]:
array1.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [68]:
array1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [69]:
array2 = np.arange(0, 10)
array2 = array2.reshape(5, 2)
array2


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [70]:
array2 + 10
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [71]:

array2 = array2 + 10
array2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

#boolean arrays

In [72]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [73]:
a[0], a[-1]

(0, 3)

In [74]:
a[[True, False, False, True]]

array([0, 3])

In [75]:
a >= 2

array([False, False,  True,  True])

In [76]:
a.mean()

1.5

In [77]:
a[a > a.mean()]

array([2, 3])

In [78]:
a[~(a > a.mean())]

array([0, 1])

In [79]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [80]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

100'e kadar rastgele tamsayılardan oluşan, 3,3 bir matris oluşturun.
30'dan büyük olanları boolean yöntemi ile filtreleyin.

In [81]:
rand_array = np.random.randint(100, size=(3,3))
rand_array

array([[41, 28,  1],
       [74, 71, 87],
       [61, 25, 23]])

In [82]:
boolean_array = rand_array > 30

In [83]:
boolean_array

array([[ True, False, False],
       [ True,  True,  True],
       [ True, False, False]])

In [84]:
rand_array[boolean_array]

array([41, 74, 71, 87, 61])

In [85]:
my_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
array_1 = my_array.reshape(5,2)
array_2 = my_array.reshape(2,5)

In [86]:
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [87]:
array_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
np.dot(array_1, array_2)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [89]:
array_2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [90]:
import sys

In [93]:
sys.getsizeof(10)

28

In [94]:
sys.getsizeof(1000**100)

160

In [95]:
np.dtype(int).itemsize

4

In [96]:
np.dtype(np.int8).itemsize

1

In [97]:
np.dtype(float).itemsize

8

In [98]:
sys.getsizeof([1, 2, 3])

88

In [99]:
np.array([1, 2, 3]).nbytes

12

In [100]:
my_list = list(range(100000))

In [101]:
my_array = np.arange(100000)

In [102]:
%time np.sum(my_array ** 2)

CPU times: total: 0 ns
Wall time: 1 ms


216474736

In [103]:
%time sum([number ** 2 for number in my_list])

CPU times: total: 0 ns
Wall time: 12.3 ms


333328333350000